version: '3.8'

services:

  # mlflow:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile.mlflow_service
  #   container_name: mlflow-service
  #   ports:
  #     - "6001:6001"
  #   volumes:
  #     - ./mlruns:/app/mlruns
  #   restart: unless-stopped
  #   healthcheck:
  #     test: [ "CMD-SHELL", "curl -f http://0.0.0.0:6001 || exit 1" ]
  #     interval: 5s
  #     timeout: 5s
  #     retries: 3

  recommender-service:
    build:
      context: .
      dockerfile: Dockerfile.recommendation_service
    container_name: recommender-service
    ports:
      - "8082:8082"
    volumes:
      - ./.git:/app/.git
    # depends_on:
    #   mlflow:
    #     condition: service_healthy
    environment:
      - SERVER_IP=127.0.0.1
      - KAFKA_PORT=9092
      - LOCAL_PORT=8082
    restart: unless-stopped
