version: '3.8'

services:
  recommender-service:
    build:
      context: .
      dockerfile: Dockerfile.recommendation_service
    container_name: recommender-service
    environment:
      - SERVER_IP=${SERVER_IP}
      - KAFKA_PORT=${KAFKA_PORT}
      - LOCAL_PORT=${LOCAL_PORT}
    ports:
      - "8082:8082"
    restart: always
