version: '3.8'

services:
  recommender-service:
    build:
      context: .
      dockerfile: Dockerfile.recommendation_service
    container_name: recommender-service
    ports:
      - "8082:8082"
    restart: unless-stopped

  mlflow:

    image: mlflow/mlflow:latest 
    container_name: mlflow-server
    volumes:
      - ./mlruns:/mlruns 
    ports:
      - "6001:6001"
    restart: unless-stopped
    command: >
      mlflow server
      --backend-store-uri file:/mlruns
      --default-artifact-root /mlruns
      --host 0.0.0.0
      --port 6001
